### ISSUE TITLE
no handler for file extension `mp3'

### ISSUE THREAD

**Issue by marminthibaut** [dadoonet/soundbeat#1]
After few seconds, I got this error stack:

```
$ ./soundbeat -c soundbeat.yml 
formats: no handler for file extension `mp3'
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4d1d68]

goroutine 7 [running]:
github.com/dadoonet/soundbeat/vendor/github.com/krig/go-sox.(*Format).Release(0x0)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/krig/go-sox/sox.go:219 +0x18
github.com/dadoonet/soundbeat/beater.(*Soundbeat).Run(0xc8200fe0f0, 0xc82008c120, 0x0, 0x0)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/beater/soundbeat.go:105 +0x107
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat.(*Beat).Run(0xc82008c120, 0x0, 0x0)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:271 +0x361
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat.(*Beat).Start(0xc82008c120, 0x0, 0x0)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:174 +0x126
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat.Run.func1(0xc82008c120)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:121 +0x3c
created by github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat.Run
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:133 +0x8d

goroutine 1 [chan receive]:
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat.Run(0x984750, 0x9, 0x0, 0x0, 0x7f6d882e0ab8, 0xc8200fe0f0, 0x0, 0x0)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:137 +0xc2
main.main()
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/main.go:12 +0xd8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 11 [select]:
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc820016eb0)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher/worker.go:54 +0x369
created by github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher/worker.go:48 +0x126

goroutine 12 [select]:
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc82001ba40)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher/bulk.go:60 +0x362
created by github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher.newBulkWorker
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/publisher/bulk.go:42 +0x20c

goroutine 13 [select, locked to thread]:
runtime.gopark(0xa59ac0, 0xc82002ff28, 0x971298, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002ff28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002ff28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 14 [chan receive]:
github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/service.HandleSignals.func1(0xc82019e7e0, 0xc820115f30, 0xc820115f20)
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/service/service.go:29 +0x3a
created by github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/service.HandleSignals
	/home/tmarmin/.go/src/github.com/dadoonet/soundbeat/vendor/github.com/elastic/beats/libbeat/service/service.go:32 +0x1f8
```

Any idea?

**Comment by marminthibaut** [comment]
Oops 
I just forgot to install a package...

**Comment by dimrizo** [comment]
Maybe tell us which package? No?
